### ISSUE TITLE
MQTT DCR request

### ISSUE THREAD

**Issue by psadeazevedo** [brunohorta82/BH-Easy-Iot#21]
As we discussed previsously I think we would need some more mqtt config being available by a simple JSON request or via web-ui. Between the changes I would love to see in the BH-PZEM the following features:

- Ability to reduce the reporting time the data is sent to the mqtt broker(currently 5 seconds could be to short for some applications). In my case would love to change to 30 or 60sec. This could be done via web-ui or either a simple curl command to change the device settings;

- I would like as well to see all topics being reported to my mqtt broker as we see it on your web UI, like the DS18B20 value;

- As well some other general counters(total consumed by day, month, year) that would make sense to exist on a power meter;

- Finally, you should consider to stream line the hack we need to do on the 004T in order to spot the signal injection for solar powered systems(not everyone has the right equipament to perform this hack)

Thank you for developing this amazing product\your support so far!

**Comment by brunohorta82** [comment]
add to dev

**Comment by brunohorta82** [comment]
add to dev
